### ISSUE TITLE
Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot'

### ISSUE THREAD

**Issue by Nashorn** [WICG/construct-stylesheets#100]
Chrome: Version 77.0.3865.120

Uncaught (in promise) TypeError: Failed to set the 'adoptedStyleSheets' property on 'ShadowRoot': Failed to convert value to 'CSSStyleSheet'.

**Comment by rakina** [comment]
Hi, for implementation-specific bugs, you can file them on crbug.com instead, and preferably with a sample code to reproduce the error. Thank you!
