### ISSUE TITLE
How does access to .cssRules behave before the sheet is "done loading"

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#11]
E.g. before all the @imports have finished.  Does it throw?  Does it allow mutation of the rule list while loads are still in progress?  Something else?

**Comment by calebdwilliams** [comment]
In the [web components issue 468](https://github.com/w3c/webcomponents/issues/468), @rniwa proposed disallowing `@import` in the constructible stylesheet spec. Not sure what the pros and cons are of that, but just trying to connect some dots.

**Comment by bzbarsky** [comment]
Disallow in what sense?  Not parsed (i.e. dropped from the rule list)?  Throws?  Not loaded?  Something else?

**Comment by calebdwilliams** [comment]
Not sure, like I said, just trying to connect some dots. For that particular issue, was hoping we would be able to fetch an external resource for `customElements` styles, but looks like @annevk agreed. Maybe someone should add this as a separate issue for discussion? I'm not sure I'm qualified to have any real opinions here, just wanting to see the thing move froward.

**Comment by annevk** [comment]
FWIW, I think this should work the same way as `<link rel=stylesheet>` or `<style>` deal with it, though as I noted in #21 we should maybe define those properly first.

**Comment by TakayoshiKochi** [comment]
Let me close this as #25 concludes we disallow `@imports`.

**Comment by TakayoshiKochi** [comment]
From the discussion at https://github.com/whatwg/html/issues/2997 (especially from Tab's https://github.com/whatwg/html/issues/2997#issuecomment-326838981), conceptually the sheet is parsed atomically, and therefore when `<link rel=stylesheet>` or `<style>`'s `.sheet` is available, its `.cssRules` is also available.

For this spec, the constuctor will produce a `CSSStyleSheet` with empty rules, and for the factory method, it returns a promise and once it resolves, its return value (a new `CSSStyleSheet` object) should have `.cssRules` ready.

So let's not make a `CSSStyleSheet` object visible until its all dependent loading/parsing is done.

(basically this adds nothing to what @annevk already said above)

**Comment by rakina** [comment]
Closed with #33 (like the above comment says, we aren't resolving Promise<CSSStyleSheet> until it's done loading)
