### ISSUE TITLE
Should the origin-clean flag be set or unset?

### ISSUE THREAD

**Issue by nordzilla** [WICG/construct-stylesheets#113]
The [spec](https://wicg.github.io/construct-stylesheets/#dom-cssstylesheet-cssstylesheet) description of the constructor notes that the [origin-clean flag](https://drafts.csswg.org/cssom-1/#concept-css-style-sheet-origin-clean-flag) should be "unset"...

> "If it is set, the API allows reading and modifying of the CSS rules."

Unsetting this flag would mean that the CSS rules cannot be read or modified. This seems wrong to me.

**Comment by rakina** [comment]
Oh right, hmm, I think this was a mistake. It should be set.
