### ISSUE TITLE
Are sheets created from the CSSStyleSheet constructor origin-clean?

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#12]
Need to define the value of https://drafts.csswg.org/cssom/#concept-css-style-sheet-origin-clean-flag on these sheets.

**Comment by TakayoshiKochi** [comment]
Looks like this is missing in the current proposal.
I was not familiar with the CSSOM spec, but it looks the origin clean flag should just be "set".

paging @zcorpan

**Comment by zcorpan** [comment]
Yeah I don't see any reason why it wouldn't be set. Code that constructs a stylesheet ought to be able to access it fully.

**Comment by TakayoshiKochi** [comment]
Oops, I might have missed something...

https://wicg.github.io/construct-stylesheets/index.html#dom-cssstylesheet-cssstylesheet
explicitly said
> Set sheet’s origin-clean flag.
