### ISSUE TITLE
Do we want to allow sharing mutable MediaLists across multiple sheets?

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#13]
Right now I believe it can't happen, but the spec draft here would allow sharing a mutable MediaList across multiple sheets.  Is this desired?  Would cloning the MediaList in the constructor be better?

**Comment by TakayoshiKochi** [comment]
Cloning the list sounds better to me.
@tabatkins what do you think?

**Comment by rakina** [comment]
+1 in cloning instead of sharing.
