### ISSUE TITLE
How are non-text/css responses handled?

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#14]
This applies at least to @import in sheets, and to the sheets themselves if loading from URL ever gets allowed.  For `<link>` and @import from link loads,  a non-text/css type for a same-origin load in quirks mode allows the sheet to be parsed.  It seems to me that we may not want that quirk here.

**Comment by TakayoshiKochi** [comment]
Good catch, I don't think we have to support legacy behavior like quirks mode, as this is for a new API.

**Comment by TakayoshiKochi** [comment]
As #25 concludes disallowing @import, let me close this.

**Comment by bzbarsky** [comment]
Um...  I don't see a conclusion in #25 that "disallows import".  Have you talked to the CSSWG about this?  You can't just go creating your own separate CSS syntax willy-nilly!

**Comment by TakayoshiKochi** [comment]
Well, sorry for the wording "conclusion" - it was not really a consensus.

**Comment by tabatkins** [comment]
Ignoring #25 for the moment tho, I agree that we shouldn't support non-`text/css` responses in this API.

**Comment by TakayoshiKochi** [comment]
@tabatkins shall we describe the response type restriction for each spec that involves any loading, or is there good one place to put all relevant information?

**Comment by tabatkins** [comment]
I suspect that each spec should define their type restrictions; there's a lot of places where things are loaded, so having a single point that tries to define all of them is probably bad. But I think @annevk would have a more useful opinion on that.

**Comment by annevk** [comment]
I'd actually expect a single point to be defined in CSS somewhere, suitably parameterized. Especially for security-sensitive code like loading you don't want too many independent decision makers.

**Comment by rakina** [comment]
#35 resolves this -  We don't handle non-`text/css`.
