### ISSUE TITLE
Define how origin is determined for a constructed stylesheet

### ISSUE THREAD

**Issue by TakayoshiKochi** [WICG/construct-stylesheets#18]
Copied from inline ISSUE 5 in the section "Applying Styles In All Contexts".

> One of the major "misuses" of the `>>>` combinator is to apply "default styles" to a component wherever it lives in the tree, no matter how deeply nested it is inside of components. The use-case for this is to provide the equivalent of the user-agent stylesheet, but for custom elements (thus, the styles by necessity must come from the author).
> Unfortunately, this is extremely slow, and there’s not a whole lot that can be done about that—`>>>` combinators are slow by their nature. Note, though, that the UA and user stylesheets automatically apply in all shadows; it’s only the author stylesheet that is limited to the context it’s created in.
> 
> (At this point, one might point out that this is already handled by just setting up styles during element construction. This doesn’t help for cases where a component is purposely authored to be styled by the end-user; forcing users of components to go muck around in their components' source code is a non-starter.)
> 
> One possible solution here is to add another origin, the "author default" origin, which sits between "user" and "author", and applies in all shadow roots automatically. We can add a list for these stylesheets, akin to document.styleSheets, and allow you to insert constructed stylesheets into it. Or maybe add an .origin attribute to CSSStyleSheet, defaulting to "author"?
> 
> Maybe it only applies to the context you’re in and descendant contexts? Need to investigate; probably bad to let a component apply automatic styles to the outer page via this mechanism.

By default, the added stylesheet via `.moreStyleSheets` property would have "author" origin, but do we also need other ("user", or "author default") origins?

We may have other interfaces to add stylesheets to different origins, or have `CSSStyleSheet` have `.origin` property?

**Comment by platosha** [comment]
It [was proposed before](https://github.com/w3c/webcomponents/blob/0e465f9f68ad01d42ab7180c9f4e1f588d30309a/proposals/Default-Stylesheets-Concept-and-Proposal.md) to add a “default” origin, and use an `@default` at-rule as an interface to add styles. Would that be an option?

Personally, I find using a dedicated at-rule reasonable. As it [was mentioned here](https://github.com/w3c/webcomponents/issues/376#issuecomment-179703991), there are reasons to ban using combinators in selectors for stylesheets with a default origin. Without an at-rule wrapping it would be weird to have special limitations on selectors in these stylesheets, unlike anywhere else.

**Comment by TakayoshiKochi** [comment]
Unfortunately people are reluctant to add a new cascading origin (esp. people at Apple) so `@default` will not happen as it is in the quoted document, at least in near future, I'd say.

**Comment by TakayoshiKochi** [comment]
This depends on the resolution of https://github.com/w3c/webcomponents/issues/468, and Google will try implementing 2 ways (one for using fake-shadow root, which is "author" origin, and the other for [default styles for custom elements](https://drafts.csswg.org/css-scoping/#default-element-styles) which is "user agent" origin).

**Comment by TakayoshiKochi** [comment]
Whatever w3c/webcomponents#468 resolves, this depends on where the constructed stylesheet is applied, and construction itself is independent of "origin" definition, as we already removed `.moreStyleSheets`.
