### ISSUE TITLE
Resolve conflict with CSS Scoping

### ISSUE THREAD

**Issue by annevk** [WICG/construct-stylesheets#22]
It seems that https://drafts.csswg.org/css-scoping/#default-element-styles "Default Styles for Custom Elements" should go if we take this approach?

**Comment by calebdwilliams** [comment]
I don't necessarily think it should go (unless I'm missing the point which is possible). I would still want some way to define default styles for a custom element (and I know @trusktr would argue for applying those styles to elements that don't include a shadow root). 

Maybe the `CSSStyleSheet` constructor should take an additional argument that is a name for the stylesheet which would then be logged to some registry. That's similar to something I proposed in the [custom elements stylesheets thread](https://github.com/w3c/webcomponents/issues/468). I could see

```javascript
const mySheet = new CSSStyleSheet('my-sheet', ` body { color: rebeccapurple; }`);
window.customStyleSheets.get('my-sheet') === mySheet; // true;

class MyElementConstructor extends HTMLElement {
  /* some element definition with or without a shadow root */
}

customElements.define('my-element', MyElementConstructor, {
  styles: ['my-sheet' | mySheet] // apply mySheet from above to this element (shadowRoot or no)
});
```

Given my limited knowledge of how browsers work, I would assume the only hazy part of that would be how `mySheet` would work without a shadow root. I'm not as married to that especially if there's some way to apply `mySheet` to a/the document.

**Comment by TakayoshiKochi** [comment]
This depends on the resolution of https://github.com/w3c/webcomponents/issues/468

**Comment by rakina** [comment]
I'm not quite sure what's the conflict with `adoptedStyleSheets`, can you elaborate @annevk?

**Comment by annevk** [comment]
Yeah, that might be somewhat separate.
