### ISSUE TITLE
Can the same constructed stylesheet be used in two different Documents?

### ISSUE THREAD

**Issue by rakina** [WICG/construct-stylesheets#23]
Should adding the same constructed stylesheet in two different Documents be allowed? If it is, can it be used as a security attack vector?

**Comment by calebdwilliams** [comment]
For the purposes of this question does "documents" include document fragments (so shadow roots) or just a `window.document`?

**Comment by ewilligers** [comment]
This question is about different `window.document` instances, e.g. from different origins. The same constructed stylesheet can certainly be used in many shadow roots under the same document - that is the primary use case.

**Comment by calebdwilliams** [comment]
I would be weary of that possibility because I can see foresee instances where library authors might want to check if the object they get is an instance of `CSSStyleSheet`. If the constructors aren’t the same, that might cause an issue (unless I’m missing the point).

**Comment by TakayoshiKochi** [comment]
I think if once a constructed stylesheet is associated with any browsing context (i.e. specified for
actual rendering), then reusing that same object to another browsing context would throw an exception
(e.g. at the point that the object is added to `.moreStyles` or whatever it ends up with).

**Comment by TakayoshiKochi** [comment]
Let's conclude that a constructed stylesheet can only be associated with one document.
I'll close this once corresponding spec draft change is done.

**Comment by rakina** [comment]
#35 resolves this. It can't be used in multiple `Document`s.

**Comment by rakina** [comment]
Reopening after @annevk's comment on https://github.com/w3c/webcomponents/issues/759#issuecomment-423160198. Maybe it's OK to make a stylesheet be usable in more than one Documents if we clearly define things that need to be defined?
 
According to #10, the URL of the stylesheet will stay the same, that is the document it is constructed on. For fetch group, we might want to use the one for the document it's constructed on? Not sure, I'll try to find out...

One of the other things that was pointed out was the security aspect - can we modify another Document's <style> element's stylesheet? If we can't, then maybe it make sense to not allow injecting a constructed stylesheet to another Document.

cc @tabatkins, who might be able to help solve these questions

**Comment by rakina** [comment]
Resolved with #61.

**Comment by rakina** [comment]
Current status is to ignore stylesheets from a different document tree. Reopening for further discussion from https://github.com/WICG/construct-stylesheets/pull/69#pullrequestreview-184929986 @emilio @bzbarsky @domenic @annevk @lilles

**Comment by emilio** [comment]
Is it very annoying implementation-wise to change the adoption algorithm in Blink? At least in Gecko we do need to iterate over the whole subtree including shadows, so I'd be surprised if that was hard to implement.

I'd also be a bit surprised if Blink didn't have to go through every adopted node and shadow tree as well.

**Comment by domenic** [comment]
I'll let @rakina answer on implementability, but from what I remember at TPAC most folks were loathe to add steps to the generic DOM tree adopting algorithm that support a CSSOM-specific feature. That felt like a layering violation. I guess upon reflection it might not be so bad; we'd just define the [adopting steps](https://dom.spec.whatwg.org/#concept-node-adopt-ext) for all shadow roots as doing this CSSOM stuff.

We additionally had the issue of how to surface errors. If the purpose is to prevent adoption, then we'd have to throw from the adopt algorithm. But that currently isn't done at all, which could have wider-ranging consequences. I think people had a few tricky examples, e.g. copying and pasting across documents.

**Comment by bzbarsky** [comment]
So my main concern with the proposed setup is that it requires the stylesheets in the adopted shadow root to hold on to the document they came from originally (via "constructor document") and thus keep it alive, even if it's now been unloaded, etc.

@emilio and I talked this over and we'd like to propose two things:

1) Setting `adoptedStyleSheets` should throw if the new list contains sheets that have the "wrong" constructor document.
2) Adopting a ShadowRoot clears out its `adoptedStyleSheets`.

That will guarantee that the sheets in `adoptedStyleSheets` always match the node document of the node involved, and prevent the accidental introduction of these cross-document memory leaks in web pages.

Thoughts?

**Comment by lilles** [comment]
That sounds good to me.

**Comment by annevk** [comment]
That does have the problem of requiring changes to https://dom.spec.whatwg.org/#concept-node-adopt which as @domenic pointed out is rather ugly. There is some precedent with `<img>` and `<template>`, but still.

**Comment by domenic** [comment]
On second thought I'm not sure I understand why the currently-specced design would require holding on to the document. We can just make the constructor document pointer a weak reference, right? Or equivalently (and probably a better implementation strategy) just compare a numeric "document ID".

Does this work, or am I totally off? I admit I'm just warming back into work-mode so might be missing something obvious.

**Comment by emilio** [comment]
The JS prototype of stylesheets created in two different documents is different. You need to somehow keep the right prototype chain around, which may involve keeping the global / document around. Though Boris can probably double-check me, I may be a bit off :)

**Comment by domenic** [comment]
Ah, right, you'll certainly have to keep at least some large object around since you can pretty quickly navigate back to the global from `sheet.constructor.constructor("this")`. You'll probably need to keep the whole graph, including the document. (I don't remember where we are on cutting parts of the object graph after navigation; IIRC it was messy and inconsistent.)

OK, nevermind that idea; thanks for the quick check!

**Comment by domenic** [comment]
Wait, no. If you're moving the adopted shadow root to a new document, then *that shadow root object* will also have the original JS prototype, so we don't gain anything by removing the document/global reference of just the adoptedStyleSheets.

I believe Gecko has a nonstandard change that swizzles the prototypes of nodes on adoption, presumably for these memory reasons, but probably you should just do another nonstandard change that swizzles the prototypes of adoptedStyleSheets when their shadow root is adopted, right? That seems more consistent with what Gecko is doing in general, while not impacting the rest of the browsers which don't do any proto-swizzling.

**Comment by bzbarsky** [comment]
The actual constructor document is needed for fetches, right?  There's a note about that in the spec.  So you need at least a weak reference; an id won't cut it unless it can be used to look up the document (at which point it's just a way of doing a weak reference).

You _could_ have a weak reference, but that presupposes that weak references are possible.  That's not a given.  Especially since you wouldn't want "constructor document" to just become null when that document goes away.

Anyway, I guess it feels like the "ignore the sheets" proposal has a lot more implementation complexity, scattered over a lot more things, than just removing the sheets on adopt.  And it requires implementations to be different from the spec's letter in subtle ways to work well.

(That's all apart from the JS prototype issue @emilio mentions.)

**Comment by domenic** [comment]
Thanks for clarifying that it would be a weak reference. I don't understand this part:

>  That's not a given. Especially since you wouldn't want "constructor document" to just become null when that document goes away.

Can you explain why weak references wouldn't be possible, or why it would be bad for the document to be null when nobody else has a reference to it?

> Anyway, I guess it feels like the "ignore the sheets" proposal has a lot more implementation complexity, scattered over a lot more things, than just removing the sheets on adopt.

Hmm, I feel the same way about making changes to adopt-a-node plus the adoptedStyleSheets setter. The "ignore the sheets" proposal just adds an extra filter clause to the list of sheets that apply, in my view.

> And it requires implementations to be different from the spec's letter in subtle ways to work well.

We could certainly spec it as a weak reference. Are there other mismatches you are referring to?

**Comment by bzbarsky** [comment]
> Can you explain why weak references wouldn't be possible

Nothing in any spec right now requires it being possible to weakly reference documents, afaict.

> or why it would be bad for the document to be null when nobody else has a reference to it?

Hmm.  I though we were still using the constructor document to detect constructed sheets, but looks like we have a separate "constructed flag" for that now.  So I was just wrong there.

> Hmm, I feel the same way about making changes to adopt-a-node plus the adoptedStyleSheets setter.

We'd just need to define adopting steps, not actually change adopt-a-node itself, right?  I agree that it's not clear how this maps onto what implementations do.

> The "ignore the sheets" proposal just adds an extra filter clause to the list of sheets that apply

Well, plus the weak ref machinery.  I agree that given the "constructed flag" it should be possible to spec the weak ref stuff the way it should be implemented, as long as all implementations are on board with it.

**Comment by domenic** [comment]
Thanks, seems like we're iterating toward two potentially-workable options. Here's my attempt at a summary, hopefully not too biased:

- Ignore the sheets (current spec as of https://github.com/WICG/construct-stylesheets/pull/69)
    - (+) A bit simpler/fewer moving pieces
    - (-) Requires Gecko to do weak references and extra proto-swizzling to maintain their anti-leaking-documents-on-adoption protection, increasing Gecko's delta from the adopting spec
- Prohibit the sheets (proposed upthread in https://github.com/WICG/construct-stylesheets/issues/23#issuecomment-449472046)
    - (+) More obvious to developers they're doing something "weird", at least when using the setter
    - (-) Requires introducing the third set of adopting steps in the platform, in a way that feels vaguely like a layering-violation (ShadowRoot depending on CSS)

Note that I think both options would need an opt-in if we ever discover a use case and want to allow cross-document usage in the future.

With these in hand, and remembering my priority of constituencies, I'm leaning a bit toward "prohibit the sheets". But I'd love to step back and give others a chance to comment or expand the pros/cons list.

**Comment by annevk** [comment]
So is the big problem here the fetch group? Hold by the document and used by the style sheet. And a fetch group gets all its fetches canceled when a document's browsing context is navigated or goes away. And using the fetch group from the new document would mess up already ongoing fetches.

Does the attempt to adopt have any impact on ongoing fetches in either solution? I.e., are they canceled? I guess since they are ignored/prohibited we'd just leave them alone.

I guess the involved solution here is for the style sheet to have its own fetch group which is reference counted from the various fetch groups of the documents it's adopted in. We have nested fetch groups (not really specified though), but the reference counting aspect would be novel.

**Comment by domenic** [comment]
Hmm, I'm not sure whether the fetch group is relevant to ignore vs. prohibit. The current spec says

>  Note: We will use the fetch group of sheet’s constructor document's relevant settings object for @import rules and other (fonts, etc) loads.
>
> Note: The rules regarding loading mentioned above are currently not specified rigorously anywhere. 

which seems "good enough"...

**Comment by annevk** [comment]
I meant that the reason folks want this strongly tied to a single document is the fetch group architecture, which albeit poorly defined, is a thing browsers have.

**Comment by rakina** [comment]
> I meant that the reason folks want this strongly tied to a single document is the fetch group architecture, which albeit poorly defined, is a thing browsers have.

Yes, it was a big reason (see #15) for not allowing multiple Document usages for now (along with complexity in implementation?)

**Comment by rakina** [comment]
After thinking about it, I think it is better to prohibit the sheets and clear the adopted sheets on adoption to a different document like  @bzbarsky's comment on https://github.com/WICG/construct-stylesheets/issues/23#issuecomment-449472046. Blink's implementation had been updated, and I'll update the spec soon.

**Comment by heycam** [comment]
@rakina can this issue be closed? I think your spec changes to follow the https://github.com/WICG/construct-stylesheets/issues/23#issuecomment-449472046 proposal were made.

**Comment by rakina** [comment]
Oops yeah forgot to actually close the issue. Thanks!
