### ISSUE TITLE
Define how / what CSP is applied to constructed stylesheet

### ISSUE THREAD

**Issue by TakayoshiKochi** [WICG/construct-stylesheets#26]
This is spun off from https://github.com/WICG/construct-stylesheets/issues/25#issuecomment-383787235.

> Should this be considered as style-inline for the purpose of CSP style-src directives? If not, what CSP style-src should we use/add?

This needs to be clarifed for construction from string, and `@import`-ed style from it (once #25 resolves to allow it).

**Comment by TakayoshiKochi** [comment]
I'm no expert on this topic, and from the glance at the [spec](https://w3c.github.io/webappsec-csp/#directive-style-src) it looks `unsafe-eval` fits for this constructor case.

I'd like to solicit from experts' opinions.

**Comment by andypaicu** [comment]
It is unfortunate but the interaction between CSSOM and CSP is not well-defined at all.

The spec does suggest `unsafe-eval` (keep in mind that section is non-normative) and it makes sense to me but it's not formalized at all in the spec.

**Comment by andypaicu** [comment]
But on the other hand, presently if you create an element in javascript and set some style on it and then add it to the document, the style-src is never involved even though you have affected the style of an element (should it be?). Maybe by that logic the answer is that style-src does not need to be involved necessarily.

**Comment by TakayoshiKochi** [comment]
@andypaicu re your https://github.com/WICG/construct-stylesheets/issues/26#issuecomment-391365041

Does the example below is a case where no CSP check is applied?
```js
let div = document.createElement('div');
div.textContent = 'Hello World';
div.style.color = 'green';
document.body.appendChild(div);
```

To help understand the case here (constructable stylesheet),
```js
let script = document.createElement('style');
script.textContent = 'your-element { color: green; }';
document.body.appendChild(style);  // Get the sheet parsed
return style.sheet;  // return constructed CSSStyleSheet
```
This is close to what happens inside an engine, but actual attachment to the body doesn't happen in a constructor, and actual style application happens when the element whose style is affected by the given styleheet is added to the document.
 
So in a sense this is similar to when `<script>` element's content is parsed, in which case [spec 6.1.12.3](https://w3c.github.io/webappsec-csp/#directive-style-src) can be applied. What do you think?

**Comment by TakayoshiKochi** [comment]
@andypaicu ping?
