### ISSUE TITLE
Define behavior when `@import` fails

### ISSUE THREAD

**Issue by TakayoshiKochi** [WICG/construct-stylesheets#27]
From @calebdwilliams https://github.com/WICG/construct-stylesheets/issues/25#issuecomment-392818571

> A follow up question is what happens when an @import fails? Does the rest of the stylesheet still parse? Say, your imported sheet is for CSS custom properties as I've outlined in #24 and the importer has fallbacks set up? For the record, this is my primary interest in @import for constructible stylesheets (composing constructed stylesheets).

**Comment by tabatkins** [comment]
I think the sheet should still parse; that matches current CSS behavior, and I don't know of anyone having trouble with that.  (If we're dispatching load events, it can send an event alerting you to this failure, but that's the extent of it.)

**Comment by calebdwilliams** [comment]
In what scenario would something like `StyleSheet.createFromString : Promise<StyleSheet>` fail then? How would we be informed that the load has failed if we can't target the imported sheet?

**Comment by tabatkins** [comment]
I wasn't intending for it to failable; it returns a Promise just so that we don't block the script on a potentially-large CSS parse.

> How would we be informed that the load has failed if we can't target the imported sheet?

As I said in my comment, this could be communicated thru load events fired on the stylesheet, maybe?

**Comment by tabatkins** [comment]
Just to make sure: in JS, if you import a module that imports sub-modules, and one of the sub-modules fails, the import as a whole still succeeds, right?  If so, then great, that's consistent with my expressed opinion (always succeed if the top-level load succeeds, maybe communicate sub-resource failures on the load event).

Whichever way it goes, tho, we should be consistent with the JS module story.

**Comment by rakina** [comment]
> Just to make sure: in JS, if you import a module that imports sub-modules, and one of the sub-modules fails, the import as a whole still succeeds, right? If so, then great, that's consistent with my expressed opinion (always succeed if the top-level load succeeds, maybe communicate sub-resource failures on the load event).
> 
> Whichever way it goes, tho, we should be consistent with the JS module story.

So I just tried it here https://glitch.com/edit/#!/simple-show and it seems like the import fails (script.js imports uppercase.js which tries to import from invalid.js that doesn't exist) and the console doesn't show the uppercase text as it should. So I guess for our case we should also not suceed? (or am I doing something wrong with the code?)

**Comment by tabatkins** [comment]
Your code looks good - if I fork it and remove the offending import, it successfully logs to the console.

So to be consistent, that suggests that any failed imports should cause the parent stylesheet's load promise to reject.

**Comment by rakina** [comment]
#35 resolves this - Failing @import means the promise is rejected.
