### ISSUE TITLE
Why methods on document instead of static factories

### ISSUE THREAD

**Issue by domenic** [WICG/construct-stylesheets#37]
This is mostly a bikeshedding issue and I don't feel strongly. But IMO the following seems nicer:

```js
const ss = await CSSStyleSheet.create(text, options);
const ss2 = CSSStyleSheet.createEmpty(options);
```

than the current spec's

```js
const ss = await document.createCSSStyleSheet(text, options);
const ss2 = await document.createEmptyCSSStyleSheet(options);
```

**Comment by rakina** [comment]
The reason of adding that was to make it not ambigous on which document the stylesheet is associated with (which is important for the URL of the stylesheet and enforcing usage in only one document) - see see https://github.com/WICG/construct-stylesheets/issues/15#issuecomment-391216056. 

I guess we can make the API be like you suggested and just make it clear in the spec, but I don't know if that will be confusing or not (maybe not really?)

**Comment by domenic** [comment]
That's a good point, and probably argues for just adding an explanation in the spec (or at least the explainer) instead of making the change.

**Comment by rakina** [comment]
Spec & explainer updated at #39.
