### ISSUE TITLE
Make processing model more precise for adoptedStylesheets getter/setter

### ISSUE THREAD

**Issue by domenic** [WICG/construct-stylesheets#41]
The spec, even after #40, does not have a clear processing model for the getter/setter of adoptedStylesheets. It should define them. Roughly something like

> Every `DocumentOrShadowRoot` has an adopted stylesheets `FrozenArray<StyleSheet>`
>
> On getting, `adoptedStylesheets` returns this `DocumentOrShadowRoot`'s adopted stylesheets.
>
> On setting, `adoptedStylesheets` performs the following steps:
> 1. Let _adopted_ be the result of converting the given value to a `FrozenArray<StyleSheet>`
> 1. Set this `DocumentOrShadowRoot`'s adopted stylesheets to _adopted_.
> 1. ... perform actual styling updates ... (unsure on right spec text for this)

**Comment by rakina** [comment]
Do we really need to write step 3 onwards? Maybe we can just say "adopted stylesheets of a `DocumentOrShadowRoot` is part of the `DocumentOrShadowRoot`'s style sheets and treated as being at the end of the style sheets" or something like that?
 
cc @tabatkins

**Comment by tabatkins** [comment]
We can match the rigor of this sort of thing in general by just saying that, yes.

This does leave timing somewhat up in the air, but that's nothing new; this should be fixed at some point, but that's a more complex interaction between several specs, and shouldn't be a blocker for this.
