### ISSUE TITLE
the asynchronous createCSSStyleSheet method isn't actually asynchronous

### ISSUE THREAD

**Issue by dbaron** [WICG/construct-stylesheets#42]
https://wicg.github.io/construct-stylesheets/#dom-document-createcssstylesheet claims to define an asynchronous method to create a style sheet, but it doesn't actually say anywhere to complete the rest of the steps in the list of steps at some later time.  That implies that it's actually defining a synchronous method.  It should probably do some (most?) of the steps later.

**Comment by domenic** [comment]
Concretely I guess the "Wait for loading of @import rules in sheet" should be done "in parallel". As written it blocks the main thread.
