### ISSUE TITLE
Why have createEmptyCSSStyleSheet()?

### ISSUE THREAD

**Issue by domenic** [WICG/construct-stylesheets#43]
Seems nicer to just have one sync constructor, `createCSSStyleSheetSync('')`. Maybe even make the string optional so you don't need to pass an empty string. (Although I guess passing nothing will be equivalent to passing `'undefined'` which will be treated as a no-op ^_^.)

**Comment by tabatkins** [comment]
It's a spandrel from before when we couldn't make a sync constructor. There's no need to have it anymore.

(And passing nothing can work, we just need to give the argument a default value in IDL. ^_^)
