### ISSUE TITLE
What  should happen when a ShadowRoot's host is adopted into a different document?

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#46]
The spec currently aims to prevent a constructed stylesheet being used across multiple documents.  We should figure out what happens when a shadow host for a `ShadowRoot` with constructed stylesheets attached is adopted into a different document.

**Comment by rakina** [comment]
I think we should move the `adoptedStylesheets` along with the shadow host & root, and keeping them as the same object, with the same base URL, like for the case of using the `CSSStyleSheet`s in different documents https://github.com/WICG/construct-stylesheets/issues/15#issuecomment-432261512

**Comment by rakina** [comment]
I think this is safe to close as #61 is merged? @bzbarsky, if you think this is still unresolved, please comment and I'll reopen.
