### ISSUE TITLE
introduction should explain why this is important for shadow DOM

### ISSUE THREAD

**Issue by dbaron** [WICG/construct-stylesheets#47]
Apparently this spec (per verbal comments in today's CSS WG meeting) is solving something that's particularly important for shadow DOM.  The introduction of the spec ought to explain what that is.

**Comment by rakina** [comment]
This is mentioned in the [explainer](https://github.com/WICG/construct-stylesheets/blob/gh-pages/explainer.md#problem-description)'s Problem Description section. Should it be put in the draft spec also?

**Comment by dbaron** [comment]
Either (a) the material in the explainer should end up in the spec or (b) the spec should link to the explainer.  I don't have a strong opinion between those options.
