### ISSUE TITLE
DocumentOrShadowRoot.adoptedStyleSheets should clearly describe its getter and setter behavior

### ISSUE THREAD

**Issue by dbaron** [WICG/construct-stylesheets#48]
https://wicg.github.io/construct-stylesheets/#using-constructed-stylesheets defines an attribute that has a getter and a setter, but it seems pretty handwavy about (a) what the setter does and (b) what the getter does.  Some of the relevant specification text seems to be above the description of the interface.  But for things with a getter and a setter I think you'll often end up with a clearer spec if you explicitly describe the getter and setter behavior.

**Comment by domenic** [comment]
Dupe of #41?

**Comment by dbaron** [comment]
Sure.
