### ISSUE TITLE
We should probably disallow inserting `@import`rules into constructed stylesheets or any of their imports

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#56]
If someone does https://drafts.csswg.org/cssom/#dom-cssstylesheet-insertrule on a constructed stylesheet, or any of its imports (or their imports, etc) and the parsed rule is an `@import` rule, we should probably throw.  Especially if we want to be able to share the sheets across documents.

**Comment by rakina** [comment]
Fixed by #61.
