### ISSUE TITLE
revisions to insertRule and deleteRule have algorithmic definitions that don't quite work

### ISSUE THREAD

**Issue by dbaron** [WICG/construct-stylesheets#68]
The revisions to `insertRule` and `deleteRule` in https://wicg.github.io/construct-stylesheets/index.html#modifying-constructed-stylesheets have a few problems:
* they use a `rule` variable that isn't defined (and fixing this probably requires inserting new bits into the *middle* of the existing algorithm)
* `insertRule` takes a different number of arguments as the original
* they use different argument names from the original

**Comment by dbaron** [comment]
(I got here from w3ctag/design-reviews#308.)

**Comment by rakina** [comment]
Ooh, yeah. And `deleteRule` shouldn't have the thing about `@import`s as well. I don't really understand what you meant by " (and fixing this probably requires inserting new bits into the middle of the existing algorithm)"? Since it's an argument to the function, can't we just reference it?

**Comment by dbaron** [comment]
The thing that's an argument to the function is just a string of text, so the thing that parses it has to come before a test of whether it's an `@import` rule.
