### ISSUE TITLE
replace(text) should throw more informative exception when @import fails to load

### ISSUE THREAD

**Issue by dbaron** [WICG/construct-stylesheets#72]
The definition of [`replace(text)`](https://wicg.github.io/construct-stylesheets/#dom-cssstylesheet-replace) currently says that the promise is rejected with `NotAllowedError` if an `@import`-ed stylesheet fails to load.  This is the same error used (as a thrown exception, rather than promise rejection) in a number of other cases.  It seems like a more informative exception should be used for load failures -- perhaps `NetworkError` or maybe even more than one (e.g., `NetworkError`, `SecurityError`) depending on what happened.

**Comment by rakina** [comment]
Yeah maybe using `NetworkError` in that case is better. Not sure about the multiple types of error thing, tried reading what happens to `insertRule` with a failed `@import` rule, seems like no exception is thrown? (from https://drafts.csswg.org/cssom/#insert-a-css-rule)

**Comment by dbaron** [comment]
Thanks.  Fix looks good to me.
