### ISSUE TITLE
Wording in "Modifying Constructed Stylesheets" is a bit confusing

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#81]
In https://wicg.github.io/construct-stylesheets/#modifying-constructed-stylesheets we have:

> If those methods are called when the sheet’s disallow modification flag is set, or insertRule(rule) is used to add an @import rule,

This sounds like it's possibly talking about the methods being called when insertRule is used to add an @import rule.

I would avoid having informative text here that sounds normative or duplicates the later algorithms.  Instead, just say:

> After construction, constructed stylesheets can be modified using rule modification methods like x, y, z.  The behavior of these methods is affected by the "disallow modification flag" and "constructed flag" as described below.

or something, to make it clear what people should keep an eye on, while not trying to duplicate the behavior definition.

**Comment by rakina** [comment]
Resolved with #88
