### ISSUE TITLE
Interaction of "constructed flag" and @import rules doesn't quite make sense to me

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#83]
https://wicg.github.io/construct-stylesheets/#dom-cssstylesheet-insertrule disallows adding an `@import` rule if "constructing flag" is set.  Why is this restriction present?

In particular, why do we allow adding an `@import` rule to a sheet imported from a sheet with the "constructed flag" but not to the parent sheet itself?

**Comment by rakina** [comment]
I think you made an issue on this: https://github.com/WICG/construct-stylesheets/issues/56, and it was also discussed in https://github.com/WICG/construct-stylesheets/issues/57#issuecomment-434027847 that we don't want to allow insertion of `@import` rules?

**Comment by bzbarsky** [comment]
#56 said "or any of their imports".  That's not what the current spec says, though: it disallows `@import` insertion into the constructed sheet, but allows it into its imports.  So the changes that were made didn't really address #56 as filed.

**Comment by rakina** [comment]
Ohh, I understand now. Can we maybe say something like "If this sheet's parent chain contains at least one sheet whose constructed flag is set, throw exception"?

**Comment by bzbarsky** [comment]
That seems fairly reasonable at first glance.

**Comment by rakina** [comment]
Resolved with #88
