### ISSUE TITLE
How should "replace" handle `@charset`?

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#84]
Normal sheet parsing strips out the first `@charset` in <https://drafts.csswg.org/css-syntax-3/#parse-a-stylesheet>.  Should `parse` do the same?  Otherwise it seems like the problem the first note at https://drafts.csswg.org/css-syntax-3/#charset-rule talks about (of valid rules getting dropped because of the invalid `@charset`) would be a problem for "replace".

@tabatkins

**Comment by tabatkins** [comment]
I'm fine with them failing in that case? People shouldn't be using `@charset` in the first place. ^_^

(This was discussed in the comments of a previous commit, where I said I think it's fine to just use the "parse a list of rules" and deal with the fallout of `@charset` rules messing up your `@import`s.)

**Comment by bzbarsky** [comment]
That seems like a problem for people who are trying to use the same sheet both normally, via `<link>`, and via the new mechanism, on different pages of their site.

I have to admit I don't understand that first note at https://drafts.csswg.org/css-syntax-3/#charset-rule by the way: `@charset` inside `@media` or whatnot does not drop following rules...  So I'm not really sure what problem this stripping is trying to solve, which makes it hard to evaluate whether it's needed here.

**Comment by tabatkins** [comment]
> That seems like a problem for people who are trying to use the same sheet both normally, via <link>, and via the new mechanism, on different pages of their site.

Only if they're using `@charset` in them, which they shouldn't be; it's a legacy feature. If they just use UTF-8, or communicate charset information via a header, it's fine either way.

-------

I don't know what you're referring to re: `@charset` inside of `@media`. That note doesn't apply to anything related to that case.

`@import` is required to be the first rule in the stylesheet, preceded only by other `@import` rules or `@charset`. ([source](https://drafts.csswg.org/css-cascade/#at-import)) The stripping handles this in a simpler manner; by the time `@import` checks, a starting `@charset` isn't there anymore.

Maybe you're referring to the fact that `@media` is defined with the `<stylesheet>` nonterminal? That doesn't invoke "parse a stylesheet", it invokes "consume a list of rules", per [its definition](https://drafts.csswg.org/css-syntax-3/#typedef-stylesheet).

**Comment by bzbarsky** [comment]
> Only if they're using @charset in them, which they shouldn't be; it's a legacy feature. If they just use UTF-8, or communicate charset information via a header, it's fine either way.

This is true if they control the linking document (and can make it be UTF-8) or the headers.  If they control neither, they are out of luck, no?  https://drafts.csswg.org/css-syntax-3/#determine-the-fallback-encoding has step 3 checking the linking document and only step 4 falling back to UTF-8.

> I don't know what you're referring to re: `@charset` inside of `@media`

I'm talking about what the existing consumers of "parse a list of rules" are.  `@media` is one such consumer, yes?  At least https://drafts.csswg.org/css-syntax-3/#parser-entry-points claims so, in a note, of course.  And https://drafts.csswg.org/css-syntax-3/#declaration-rule-list says that "consume a list of rules" should be used, though without specifying the flag value that needs as input...

> That note doesn't apply to anything related to that case.

OK, what case does the note apply to, then?

> The stripping handles this in a simpler manner; by the time @import checks, a starting `@charset` isn't there anymore

Yes, I understand the general intent.  I don't quite understand the mechanism involved and how it actually works.  What happens if there are two `@charset` at the front?  What I would expect to happen is that the first one is used for encoding information, then both are dropped from the rule list as invalid rules and any `@media` that come after them work fine.  But I can't tell whether that's what https://drafts.csswg.org/css-syntax-3/#parse-a-stylesheet ends up doing, and I somewhat suspect it's not.

**Comment by tabatkins** [comment]
> This is true if they control the linking document (and can make it be UTF-8) or the headers. If they control neither, they are out of luck, no?

Sure, but using anything but UTF-8 for *anything* is honestly legacy, so eh.

> OK, what case does the note apply to, then?

What I just said - parsing a stylesheet, to ensure that `@import` works properly.

> What happens if there are two @charset at the front? What I would expect to happen is that the first one is used for encoding information, then both are dropped from the rule list as invalid rules and any @media that come after them work fine.

This might explain some of my confusion - do you mean `@import` here and in previous comments? There's no positioning requirement for `@media` at all.

If I pretend you meant `@import`, then as currently written in the spec, hm, I'm indeed not sure what dropping accomplishes. What happens is indeed what you describe - the two `@charset`s are invalid rules and get dropped, so they have no effect on a following `@import` (just as any other invalid rule would; an `@foo;` behaves the same way.

I'm vaguely recalling that maybe browsers used to keep the `@charset` rules in the stylesheet, but dropped the first one if it was valid? That would explain my "drop" behavior; if I then later added the "it's not even a rule at all", that ends up invalidating the reasoning for stripping the first charset.

**Comment by bzbarsky** [comment]
> What I just said - parsing a stylesheet, to ensure that @import works properly.

Right, I understand that part.  What I'm not sure about is why we want different rules for parsing sheets in `replace` from every single other place where we parse sheets.

> do you mean `@import` here and in previous comments

Er, I mean `@import` here, but _not_ in previous comments.

> I'm vaguely recalling that maybe browsers used to keep the @charset rules in the stylesheet

This used to be true, yes.

> but dropped the first one if it was valid?

Gecko certainly never did anything of the sort.  Dunno about others.

OK.  So if `@charset` just get dropped as invalid rules, seems like we should just remove the manual "drop" behavior and then this issue can be closed as not having anything to talk about.  :)

**Comment by tabatkins** [comment]
> seems like we should just remove the manual "drop" behavior and then this issue can be closed as not having anything to talk about. :)

I think so! I'll open a CSSWG issue. ^_^
