### ISSUE TITLE
How can one detect when the sheet is "done loading"?

### ISSUE THREAD

**Issue by bzbarsky** [WICG/construct-stylesheets#9]
If the sheet has @import rules, how can the API consumer tell when the sheet is done loading all the imports and is ready to be used?

**Comment by TakayoshiKochi** [comment]
One idea would be making `CSSStyleSheet` an `EventTarget`, so that `load` event can be dispatched when all the dependencies are complete.  The other idea would be adding a method that returns a promise which resolves at everything is ready.

**Comment by calebdwilliams** [comment]
Is there an equivalent for a typical `HTMLStyleElement`? If there is, I would think matching that as closely as possible would be ideal.

**Comment by bzbarsky** [comment]
`HTMLStyleElement` is an `EventTarget` and fires load/error events (though in some browsers those are pretty buggy).

**Comment by TakayoshiKochi** [comment]
One of the motivation for having this (for custom elements default style or any shadow roots) is not only for memory saving to share the multiple instance of the same stylesheet among all the shadow trees, but also avoid firing "load" event for every <style> element in each shadow tree instance.

In that context, firing only one "load" event for an constructed instance (not when added to shadow tree) sounds good.

**Comment by TakayoshiKochi** [comment]
As #25 concludes disallowing `@import`, it makes little sense to dispatch a `load` event on the constructed stylesheet, which should be ready.

Let's revisit this once #2 (asynchronous parsing) or URL-based construction is considered.

**Comment by tabatkins** [comment]
Reopening because #25 is not actually resolved.

**Comment by rakina** [comment]
From https://github.com/WICG/construct-stylesheets/issues/11#issuecomment-402947865, we don't want to expose the CSSStyleSheet when it's not done loading, so we know it's done loading when the promise is resolved.

**Comment by rakina** [comment]
Closed with #33 (with what I said in the previous comment)
