### ISSUE TITLE
Higher Level of Abstraction

### ISSUE THREAD

**Issue by Randy-Buchholz** [WICG/construct-stylesheets#91]
Does implementing a higher level of abstraction for stylesheets make sense as these become more like standard objects? Especially with the Typed CSSOM coming? It seems there are a lot of boilerplate hoops to jump through when adding and retrieving stylesheets that could be moved down into implementation details.

To explain, a basic use case is to create a stylesheet, store it,  and then use or manipulate it.
But there needs to be a way to find it. With constructibles, I can do basic creation, with `const ss = new CSSStyleSheet();`. Eventually, it needs to be attached to a document, but for now, it is just a stand alone object. Once attached to a document, it will be available in `document.stylesheets`. One thing the object is missing at this point is a "self identity". There is a place on the object to hold an identity - `title`.  This could be set in the constructor - `const ss = new CSSStyleSheet("componentFooStyles");`.

From an end developer perspective, I now just want to save it and be able to retrieve it. - "it" being the sheet named "componentFooStyles" and referenced by "ss". In most cases, storing it means adding a node to the "active" document. But at a conceptual level, I just want to add it to the `document.stylesheets` collection. Shouldn't it be as simple as `document.stylesheets.add(ss)`? (Understanding that under the hood, it is getting added to the document and only viewed through the collection.) On the flip side, getting a reference to the sheet should be as simple as `const ssModifying = document.stylesheets["componentFooStyles"]`.

Of course, there are things (like name collisions, etc.) to consider. But shouldn't the dev environment reflect the way we think - objects and collections, and more of what is under the hood - DOM and CSSOM?

**Comment by domenic** [comment]
I can't really understand what this issue is asking. Can you state what bug you've found in the spec, or what use case you're trying to accomplish that isn't possible with the current set of CSS specs?

**Comment by Randy-Buchholz** [comment]
I don't think there are any bugs or problems, it's more of an ease of use thing. It may just be the way I think about this. It always seemed like it's a legacy thing that CSS is part of the document itself - it is really something applied to the DOM structure - the DOM does not depend on the internal/internally linked existence of the CSS .  With constructibles and typed I can view CSS more like plain objects. It seems awkward that with construct CSS I would create an object, convert it to a node, and add it to the document, only to have the engine break it out for the CSSOM.

In my specific case, I'm using WebSockets and Web Workers to dynamically build what is in the main thread. Basically, I'm trying to make the browser window little more than a "Lean" View. Scripts and even un-displayed html stays in a worker until they need to be used or displayed. I end up with script, css, and html fragments that are moved in and out of the View. So the idea of "the document" changes a little for me. I see the window, with interacting collections of scripts, styles, and html components. The document is the state of these interactions. I'll load a couple of html components into the View, add some CSS and ES components, and then bind them together. The mechanics of adding them means adding them to the document as nodes, with boilerplate create/append functions. To get styles, I need to get `document.stylesheets` and search for a `title`. I've created a `DomDriver` to do all of this for me, but it seems unnecessary.

So, (going out a limb here), I've been wondering if the document-centric approach is outdated. If the engine parses scripts, CSS, and html into separate areas for processing, what is the value of putting them into the document in the first place? Of course, this isn't going to change in the engines any time soon, if ever. But constructible stylesheets seem to enable a step. If I can create a stylesheet object, the longer I can keep it an object (vs text to parse), possibly the better. At some point, the engine might be able to use these objects directly.

The idea is, that if the CSS Browser API supports CSSStyleSheet collections directly, that begins to open some options. For example, `stylesheets` could be moved from document to window - `window.stylesheets`, removing (what I see as) an unnecessary dependency. Or, engines might possibly be able to process collections of objects more efficiently than collections of CSS text blocks.

So, the ask would be two things I guess.

1) Add a constructor that sets `title` to give the CSSStyleSheet a self identity - `new CSSStyleSheet(title)`.
2) Add an abstraction over the `<style>` blocks in `document` to `window` (ideally, or document) that supports `CSSStyleSheet` objects, with
- `window.stylesheets.add(CSSStyleSheet object)`
- `window.stylesheets.get(CSSStyleSheet.title)` or `window.stylesheets[CSSStyleSheet.title]`

This would be a step towards a more module/component based, and less document centric, approach.

**Comment by domenic** [comment]
This is a lot of text to read, but I can't really understand what's wrong with the current system. Titles are an outdated feature for the old "alternate stylesheet" abilities that are no longer exposed in most (all?) browser UIs. And you can already add things to `adoptedStyleSheets` as specified in this document. Whether that's on document or window is not really a big deal.

If you want to build your own way of tracking stylesheets based on strings, you're very welcome to. But it's unclear what new capabilities that gives you, and as such why it'd be worth investing the effort in speccing, writing tests, and implementing it in four browsers.

You may also find it a good idea to apply the steps in https://whatwg.org/faq#adding-new-features. In particular, I still can't understand from this long thread what actual use cases you're targeting. A succinct description (that means "one or two sentences") stating what you want to do, and why it's not possible today, would go a long way.

**Comment by Randy-Buchholz** [comment]
Sorry for the long-winded post. And it's likely I'm in the wrong place. This is probably more a browser thing than a CSS spec thing. I guess basically I'm wondering why I can't directly add a stylesheet to the stylesheet collection. I understand that the exposed collection is a read only view, but it seems that if I will be able to create a stylesheet object in code, I would want to be able to just add that object to the collection of stylesheets. I seem to be missing something basic.

**Comment by domenic** [comment]
You can add a styleSheet to a document or shadow root by settings its adoptedStyleSheets property appropriately. See the examples in the spec, in the explainer, or in https://developers.google.com/web/updates/2019/02/constructable-stylesheets

**Comment by Randy-Buchholz** [comment]
Cool. Thanks.
