### ISSUE TITLE
constructible versus constructable

### ISSUE THREAD

**Issue by Lonniebiz** [WICG/construct-stylesheets#96]
Which word is correct, constructible or constructable?

https://wikidiff.com/content/constructable-vs-constructible-whats-difference-0

All stylesheets can be constructed, the essence of this feature is that you can reference the stylesheet, within the shadowDOM, efficiently, like you would an object or an array: assign-by-reference.

I don't like the name, but I do appreciate the concept and look forward to it being implemented in all browsers.

**Comment by domenic** [comment]
Dupe of #90.
